name: Sync package.json with repo info
description: GitHub Action that syncs package.json wpository metadata (description, homepage, topics/keywords).
author: Jaid
runs:
  using: node12
  main: build/index.js
branding:
  icon: refresh-cw
  color: green
inputs:
  githubToken:
    description: Repository token for allowing the action to make commits or change the repository info. If direction is "overwrite-file", this input be set from forwarding secrets.GITHUB_TOKEN in the workflow file. If direction is "overwrite-github", a custom personal access token with "repo" scope has to be created.
    required: true
  approve:
    description: If true and direction is "overwrite-file", pull requests created by this action are automatically approved and merged.
    default: "true"
    required: false
  removeBranch:
    description: If true and direction is "overwrite-file" and approve is also true, automatically merged pull requests will delete their branch afterwards.
    default: "true"
    required: false
  commitMessagePrefix:
    description: Prefix string used in messages for automatically generated commits
    default: "autofix: "
    required: false
  syncDescription:
    description: If true, package.json[description] will be synced with GitHub repository description.
    default: "true"
    required: false
  syncHomepage:
    description: If true, package.json[homepage] will be synced with GitHub repository homepage.
    default: "true"
    required: false
  syncKeywords:
    description: If true, package.json[keywords] will be synced with GitHub repository topics.
    default: "true"
    required: false
  direction:
    description: The syncing direction, can be "overwrite-file" or "overwrite-github". If "overwrite-file", the file package.json will be edited in a pull request according to the GitHub repository info. If "overwrite-github", the GitHub repository info will be changed according to the content of the package.json file.
    default: "overwrite-file"
    required: true