name: Sync package.json with repo metadata
description: GitHub Action that syncs package.json with the repository metadata (description, homepage, topics/keywords).
author: Jaid
runs:
  using: node12
  main: build/index.js
branding:
  icon: refresh-cw
  color: green
