name: Validate and autofix
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.3.4
      - name: actions/setup-node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "14.15.3"
      - name: npm install
        uses: jaid/action-npm-install@master
      - name: Jest
        uses: jaid/action-jest@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Node Meta
        uses: jaid/action-sync-node-meta@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Uptodater
        uses: jaid/action-uptodater@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fix: "true"
          approve: "true"